### ISSUE TITLE
Multiple Cameras and Lidar together

### ISSUE THREAD

**Issue by dkhanna511** [beltransen/velo2cam_gazebo#10]
Hey, thanks for the great work. 
I wanted to know if we can calibrate more than 2 sensors at one with this process. If we have multiple black fly camera monocular cameras and a single VLP16 LIDAR, can the complete setup be calibrated together?

**Comment by beltransen** [comment]
Hi @dkhanna511.
Our calibration software is built to calibrate pairs of sensors. In case you have more than 2 modalities, you will need to perform the calibration process several times. 

An implementation of the overall calibration you are mentioning is not in our roadmap because it may require the use of several calibration targets, as the field of view of all sensors may not overlap, losing the simplicity of the current version.
