### ISSUE TITLE
Remove velodyne_gazebo_plugin

### ISSUE THREAD

**Issue by kmhallen** [beltransen/velo2cam_gazebo#2]
Would you consider removing the velodyne_gazebo_plugin package that was copied from [DataspeedInc/velodyne_simulator](https://bitbucket.org/DataspeedInc/velodyne_simulator/) now that issue [vertical-laser-beams-appearing-higher](https://bitbucket.org/DataspeedInc/velodyne_simulator/issues/4/) has been addressed? I believe that is the only change you've made here.

I am only trying to reduce code duplication. You are completely within the BSD license to copy and change the code.

If there are any other changes you would like, let me know or raise an issue on the main repo.

By the way, I found out about this repository from a development [build](http://build.ros.org/job/Kdev__velo2cam_gazebo__ubuntu_xenial_amd64/1/console#console-section-1) failure email.

**Comment by beltransen** [comment]
Hi kmhallen,
Good to know the issue is already solved! We will check if there are any other changes and in case there aren't, we will proceed to the removal of the plugin in our repo. 
Btw, sorry about the dev build email you received =) , it was the first time we were submitting a package to ROS wiki and we forgot to change the package.xml of the plugin.

**Comment by kmhallen** [comment]
Awesome! Sounds good to me.
