### ISSUE TITLE
Using velo2cam_gazebo with certain PCL versions

### ISSUE THREAD

**Issue by shulace13** [beltransen/velo2cam_gazebo#3]
Hi, 

I'm using your velo2cam codes on several computers.
They all have pretty much the same environment except for the version of the PCL.

The ones with PCL ver. 1.7.2 works fine, but the ones with 1.8 it doesn't.
When I try to execute
roslaunch velo2cam_gazebo real_stereoHDL32_zero.launch
it returns this message.
[gazebo_gui-3] process has died [pid 7280, exit code 132, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/amsl/.ros/log/dede5ac2-e2e5-11e7-b7d8-309c230ad142/gazebo_gui-3.log].
log file: /home/amsl/.ros/log/dede5ac2-e2e5-11e7-b7d8-309c230ad142/gazebo_gui-3*.log

Is it just a problem with my computer's GPU memories or is it a problem with the PCL versions.

Thank you in advance.

**Comment by beltransen** [comment]
Hi @shulace13, the node that is crashing seems to be the GUI of the Gazebo simulator. This is not a ROS node we have developed, so we don't know where the problem is coming from since it has never happened to us. I recommend you to look at the [Gazebo repository](https://github.com/ros-simulation/gazebo_ros_pkgs) and check if anyone has faced the same error before.

**Comment by shulace13** [comment]
I see... I will go check it out! Thank you for replying!
