### ISSUE TITLE
How can i get lidar and camera tf information?

### ISSUE THREAD

**Issue by lemon5254** [beltransen/velo2cam_gazebo#8]
hello~
when i roslaunch velo2cam_gazebo real_stereoVLP16_roll.launch
and then see rostopic list

i can't find tf topic
how can i get it?

**Comment by beltransen** [comment]
Hi @lemon5254 , the /tf topic is not published when running gazebo simulator. This .launch file only starts the simulator with a specific calibration scenario. The parameters of the pre-defined scenarios can be found in the paper.

**Comment by lemon5254** [comment]
@beltransen thanks! can i ask a question?
so how can I see the calibration result in rviz?
I don't know how to fusion lidar and camera in same window.
When i play the velo2cam_calibration bag file  i only can see like the picture
![RViz-_006](https://user-images.githubusercontent.com/58410528/71057558-0f14fa00-2198-11ea-9ec1-beb8d5bc51e5.png)

**Comment by beltransen** [comment]
Once you run the calibration algorithm, a calibrated_tf.launch file will be created. You can launch it in order to see both the camera and LiDAR in Rviz. If you want to see it before using our package, you can create your own [static transform broadcaster](http://wiki.ros.org/tf#static_transform_publisher) and publish the correct TF specified in the paper for the corresponding scenario.

**Comment by lemon5254** [comment]
OK thanks!!!!!!!!

**Comment by dkhanna511** [comment]
> OK thanks!!!!!!!!

Hi @lemon5254 , where do you find the path for calibrated_tf.launch?

**Comment by Enes1097** [comment]
@dkhanna511 If you're still looking for them, you can find them under the directory catkin_ws/src/velo2cam_calibration/launch.
Catkin_ws is the workspace in which you cloned the velo2cam repository.
